### ISSUE TITLE
taking stuff to the symposium

### ISSUE THREAD

**Issue by jerabaul29** [jvoermans/Wind_Input_V1#18]
@jvoermans if you are able to take a full prototype in your luggage to the symposium that would be great, then we can surely have a small hackaton to fix possible issues / do some testing etc :) . If you do not have enough space to take everything (but I guess it should be quite compact?), maybe you can take at least the 2 pressure sensors (I think I can get my hand on most of the other stuff :) ).

**Comment by jvoermans** [comment]
That should be possible :)
