### ISSUE TITLE
timeline

### ISSUE THREAD

**Issue by jerabaul29** [jvoermans/Wind_Input_V1#19]
@jvoermans can you remind me of the timeline (when do you have to ship?)

From my side, some good news, I thing I found and fixed quite a few bugs, should be relatively easy sailing forward (crossing fingers :) ).

I let you know as soon as I have a true v1 you can test :) .

**Comment by jvoermans** [comment]
Perfect! I have to ship it around 15-April :)

**Comment by jerabaul29** [comment]
Good. I should have some stuff to test for you by the end of this week or this weekend hopefully, then it should be plenty of time for you to build :) . (guess you already have all the components, so it is "just" a matter of assembling? :) )
