### ISSUE TITLE
pressure sensor: BMP390 vs DPS310

### ISSUE THREAD

**Issue by jerabaul29** [jvoermans/Wind_Input_V1#20]
Sorry if we discussed this long ago and I just forgot...

Just being curious: if I understand well, you want to use the BMP390, right? Any reason for not choosing the DPS310, that is supposed to be much better? Did you test both or similar?

**Comment by jerabaul29** [comment]
Sorry I was confused because some datasheet use Pa, some hPa, and people mess things up in their tests ^^ . According to datasheets

- https://www.mouser.com/pdfDocs/bst-bmp390l-ds001.pdf
- https://www.infineon.com/dgdl/Infineon-DPS310-DataSheet-v01_02-EN.pdf?fileId=5546d462576f34750157750826c42242

the BMP should be better :) .

I think the product pages of adafruit are quite confusing too...

If you can confirm if you have looked into this comparison in details will be interesting though :) . If not, may be worth buying a couple of both sensors, and testing / comparing them :) .

**Comment by jvoermans** [comment]
BMP390 should be the best of the low-cost at the time I was looking at it :)
Quick glance, BMP390 is slightly better than the DPS310, which looks a lot like the BMP388 from the datasheet

Bosch also has a new one: BMP384. Not better in accuracy, but seems to be able to measure faster which could be interesting. Also this one seem weather (not water) resistant, which can be helpful. Sparkfun has a breakout. But perhaps stick with the BMP390...

**Comment by jerabaul29** [comment]
Sticking to the BMP390 sounds good :) .
