### ISSUE TITLE
choice of parameters

### ISSUE THREAD

**Issue by jerabaul29** [jvoermans/Wind_Input_V1#21]
@jvoermans ,

- any reason for choosing 20Hz update frequency instead of 10Hz? I wonder if it would be easier to get things working with 10Hz, would this be a problem?
- in particular regarding the BMP390: looking at the datasheet: https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmp390-ds002.pdf 3.9.1, "Measurement time", the highest resolution is only running at worst case around 12Hz.

**Comment by jvoermans** [comment]
The 20Hz has post-processing advantage over 10Hz. But 10Hz is fine too.
There are some features on the BMP390 which improve measurements, but at a cost of lower sampling rate. I think the 12Hz refers to that... I think maximum we can get with the settings I prefer is 22.5 Hz or something if I remember correctly.

**Comment by jerabaul29** [comment]
Ok, I can go for 20Hz if it is better for post processing, there should be enough RAM etc for that :) .

Yes, there is a trade-off frequency vs accuracy. I can choose a mode with lower accuracy but better frequency so things work at 20 Hz :) .

**Comment by jerabaul29** [comment]
set to 20Hz
