### ISSUE TITLE
ready for some tests :)

### ISSUE THREAD

**Issue by jerabaul29** [jvoermans/Wind_Input_V1#22]
@jvoermans , I think I have something working now, at least ready to do some cycles of test + debug, but works on some small tests I have been doing on my end for a few tens of minutes.

The branch to look at:

- https://github.com/jvoermans/Wind_Input_V1/tree/logger_version_jr
- please note small differences around the wiring of the GPS, see the readme (and the png picture, but I think it will be hard to see). You will need a 1kOhm resistor to pull down the GPS EN to make sure it is off when not needed (I think this will reduce power consumption by like 90% compared to having the GPS always on, down to a few mA in IMU + pressure logging).
- also note that for the real world loggers, you should include the battery on the GPS breakouts, otherwise the GPS fix taking may take too long compared with the logging duty cycle, and you may loose some logging sections if the GPS fix takes too long and you miss the "start" of a logging section (as logging section will start each UTC minute % 10 == 0, and will last 8 minutes, so you only have a couple of minutes to get the "data start" and "data end" gnss fixes).

Let me know if anything is unclear :) .

- there may be bug, but the most you run and debug (I will run and debug too), the more bugs we will take away :)
- for now I only log 1 pressure sensor, but it will be very easy to log 2 (all the code is in place; it is just that I found a BMP390 lying around, but I have only 1, so to be able to test locally, I only have 1 enabled now)
- I am working on the binary SD card decoder, I let you know when I have a draft ready (may take a couple more days)

All in all, I am pretty happy with the tests so far, crossing fingers that it is not so far from a good working solution you will be happy with :) .

Let me know if you have any questions / if anything is unclear.

Maybe we can iterate a bit in the days to come, and plan for a meeting next week or the week after next? :)

**Comment by jerabaul29** [comment]
(working on the decoder, hope to have a prototype tomorrow, but feel free to build + run the logger in the meantime to generate some test data :) ).

**Comment by jerabaul29** [comment]
(if you have time of course, no hurry otherwise :) but the more test hours we clock, the better debugged :) if you can also generate some time series moving the imu + pressure sensor up down for example, that would be great; the system is logging when the blue artemis redboard led is blinking "fast" (at around 1 Hz))

**Comment by jerabaul29** [comment]
(will need a gnss fix to be able to log, otherwise it will just "try again later"; you can see "as usual" the output on serial over USB, baudrate 1000000, that should give you an idea of what is happening :) )

**Comment by jvoermans** [comment]
Great! Thanks so much. I'll see if I can find time to test it today :)

**Comment by jvoermans** [comment]
Not able to get it logging for some reason. All wires double checked, EN pin to digital 2, and 1kOhm between EN and GND.
SD-card remains empty (also checked with ls). Blue light is also not blinking during GPS connection.

The GPS also keeps blinking initially at 1Hz (i.e., no GPS connection yet) during the 'sleep for 11 seconds' part. I assume it shouldn't?

Can you see from the output of Serial where it is going wrong for me?

```
--- Terminal on COM16 | 1000000 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
10:52:15.769 > WindInput logger | https://github.com/jvoermans/Wind_Input_V1
10:52:15.772 > Compiled: Mar  9 2023, 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
10:52:15.772 > git branch: DUMMY | commit ID: DUMMY
10:52:15.780 > compiling hostname: DUMMY | username: DUMMY
10:52:15.793 > Chip ID: 15245007187966232465
10:52:15.802 > ***** all user configs start *****
10:52:15.802 > use_usb: 1
10:52:15.802 > file_start_modulo_seconds: 600    
10:52:15.803 > ***** all user configs end   *****
10:52:15.813 > gnss turn on    
10:52:15.813 > gnss enable high
10:52:15.915 > gnss start serial
10:52:16.025 > gnss send commands
10:52:16.228 > gnss done turn on
10:52:16.730 > gnss turn off
10:52:16.730 > gnss enable low
10:52:16.831 > gnss end uart
10:52:16.932 > gnss done turn off
10:52:16.932 > sleep for 11 seconds
10:52:28.791 > wakeupsetup init GPS, get first fix, set RTC clock
10:52:28.792 > gnss get good averaged fix
10:52:28.792 > gnss turn on
10:52:28.792 > gnss enable high
10:52:28.894 > gnss start serial
10:52:29.004 > gnss send commands
10:52:29.208 > gnss done turn on
10:52:29.307 > gnss get first fix
10:52:29.307 > gnss start grab uart output
10:52:29.308 > $PMTK001,314,3*36
10:52:29.308 > gnss received NMEA end
10:52:29.308 > $PMTK001,220,3*30
10:52:29.309 > gnss received NMEA end
10:52:29.310 > $GPRMC,235216.000,A,3747.9335,S,14457.7068,E,0.14,0.00,080323,,,A*7C
10:52:29.312 > gnss received NMEA end
10:52:29.313 > gnss NMEA parsed valid
10:52:29.313 > gnss NMEA is RMC
10:52:29.313 > gnss fill output fix
10:52:29.314 > $PMTK001,314,3*36
10:52:29.314 > gnss received NMEA end
10:52:29.315 > $PMTK001,220,3*30
10:52:29.315 > gnss received NMEA end
10:52:29.315 > $GPRMC,235217.000,A,3747.9336,S,14457.7068,E,0.04,0.00,080323,,,A*7F
10:52:29.318 > gnss received NMEA end
10:52:29.318 > gnss NMEA parsed valid
10:52:29.318 > gnss NMEA is RMC
10:52:29.319 > gnss fill output fix
10:52:29.319 > $PMTK001,314,3*36
10:52:29.319 > gnss received NMEA end
10:52:29.321 > $PMTK001,220,3*30
10:52:29.321 > gnss received NMEA end
10:52:29.322 > $GPRMC,235229.000,A,3747.9602,S,14457.6891,E,0.80,220.82,080323,,,A*79
10:52:29.667 > gnss received NMEA end
10:52:29.668 > gnss NMEA parsed valid
10:52:29.668 > gnss NMEA is RMC
10:52:29.668 > gnss fill output fix
10:52:29.670 > $GPRMC,235230.000,A,3747.9604,S,14457.6886,E,0.12,220.82,080323,,,A*7A
10:52:30.667 > gnss received NMEA end
10:52:30.668 > gnss NMEA parsed valid
10:52:30.668 > gnss NMEA is RMC
10:52:30.668 > gnss fill output fix
10:52:30.670 > $GPRMC,235231.000,A,3747.9605,S,14457.6883,E,0.56,220.82,080323,,,A*7F
10:52:31.668 > gnss received NMEA end
10:52:31.669 > gnss NMEA parsed valid
10:52:31.669 > gnss NMEA is RMC
10:52:31.669 > gnss fill output fix
10:52:31.671 > $GPRMC,235232.000,A,3747.9604,S,14457.6884,E,0.55,220.82,080323,,,A*79
10:52:32.668 > gnss received NMEA end
10:52:32.668 > gnss NMEA parsed valid
10:52:32.668 > gnss NMEA is RMC
10:52:32.669 > gnss fill output fix
10:52:32.669 > $GPRMC,235233.000,A,3747.9602,S,14457.6885,E,0.52,220.82,080323,,,A*78
10:52:33.670 > gnss received NMEA end
10:52:33.671 > gnss NMEA parsed valid
10:52:33.671 > gnss NMEA is RMC
10:52:33.671 > gnss fill output fix
10:52:33.672 > $GPRMC,235234.000,A,3747.9600,S,14457.6887,E,0.56,16.63,080323,,,A*43
10:52:34.666 > gnss received NMEA end
10:52:34.667 > gnss NMEA parsed valid
10:52:34.667 > gnss NMEA is RMC
10:52:34.667 > gnss fill output fix
10:52:34.668 > $GPRMC,235235.000,A,3747.9600,S,14457.6887,E,0.53,16.63,080323,,,A*47
10:52:35.670 > gnss received NMEA end
10:52:35.670 > gnss NMEA parsed valid
10:52:35.670 > gnss NMEA is RMC
10:52:35.671 > gnss fill output fix
10:52:35.671 > $GPRMC,235236.000,A,3747.9599,S,14457.6888,E,0.49,16.63,080323,,,A*43
10:52:36.670 > gnss received NMEA end
10:52:36.670 > gnss NMEA parsed valid
10:52:36.670 > gnss NMEA is RMC
10:52:36.671 > gnss fill output fix
10:52:36.671 > $GPRMC,235237.000,A,3747.9597,S,14457.6889,E,0.50,16.63,080323,,,A*45
10:52:37.670 > gnss received NMEA end
10:52:37.671 > gnss NMEA parsed valid
10:52:37.671 > gnss NMEA is RMC
10:52:37.671 > gnss fill output fix
10:52:37.672 > $GPRMC,235238.000,A,3747.9595,S,14457.6890,E,0.51,16.63,080323,,,A*41
10:52:38.669 > gnss received NMEA end
10:52:38.670 > gnss NMEA parsed valid
10:52:38.670 > gnss NMEA is RMC
10:52:38.670 > gnss fill output fix
10:52:38.671 > $GPRMC,235239.000,A,3747.9594,S,14457.6892,E,0.51,16.63,080323,,,A*43
10:52:39.669 > gnss received NMEA end
10:52:39.669 > gnss NMEA parsed valid
10:52:39.669 > gnss NMEA is RMC
10:52:39.669 > gnss fill output fix
```

**Comment by jerabaul29** [comment]
Strange.

- are you sure you use the latest commit?
- are you sure the wiring is identical to the readme of my branch (in particular, GPS gets power from Vin not 3.3V)
- do you have GPS coverage (if not it will not enter into log mode)

From mine: (note: I do not have a battery on the GPS, so it takes even more fixes before getting a fix)

```
07:30:36.404 > WindInput logger | https://github.com/jvoermans/Wind_Input_V1
07:30:36.405 > Compiled: Mar  9 2023, 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
07:30:36.406 > git branch: logger_version_jr | commit ID: db92086fcedc2704fc008cdf067b145180ecd7c7
07:30:36.417 > compiling hostname: L590 | username: jrmet
07:30:36.429 > Chip ID: 3063140477490955048
07:30:36.438 > ***** all user configs start *****
07:30:36.438 > use_usb: 1
07:30:36.438 > file_start_modulo_seconds: 600
07:30:36.438 > ***** all user configs end   *****
07:30:36.449 > gnss turn on
07:30:36.449 > gnss enable high
07:30:36.551 > gnss start serial
07:30:36.661 > gnss send commands
07:30:36.862 > gnss done turn on
07:30:37.361 > gnss turn off
07:30:37.361 > gnss enable low
07:30:37.463 > gnss end uart
07:30:37.561 > gnss done turn off
07:30:37.561 > sleep for 11 seconds
07:31:46.918 > wakeupsetup init GPS, get first fix, set RTC clock
07:31:46.919 > gnss get good averaged fix
07:31:46.919 > gnss turn on
07:31:46.919 > gnss enable high
07:31:47.022 > gnss start serial
07:31:47.131 > gnss send commands
07:31:47.333 > gnss done turn on
07:31:47.431 > gnss get first fix
07:31:47.431 > gnss start grab uart output
07:31:47.431 > $PGACK,103*40
07:31:47.432 > gnss received NMEA end
07:31:47.432 > $PGACK,105*46
07:31:47.432 > gnss received NMEA end
07:31:47.432 > $PMTK011,MTKGPS*08
07:31:47.433 > gnss received NMEA end
07:31:47.434 > $PM$PGACK,103*40
[plenty of outputs until gets fix... if the fix times out, go to sleep for 15 minutes before trying again]
07:34:10.065 > $GPRMC,063409.000,A,5956.4134,N,01040.6461,E,0.04,157.11,090323,,,A*67
07:34:10.139 > gnss received NMEA end
07:34:10.140 > gnss NMEA parsed valid
07:34:10.140 > gnss NMEA is RMC
07:34:10.140 > gnss fill output fix
07:34:10.140 > gnss compute nsigma fix
07:34:10.141 > --- gnss good average fix start
07:34:10.142 > output_fix.posix_timestamp: 1678343640
07:34:10.142 > output_fix.year: 2023
07:34:10.142 > output_fix.month: 3
07:34:10.143 > output_fix.day: 9
07:34:10.143 > output_fix.hour: 6
07:34:10.143 > output_fix.minute: 34
07:34:10.143 > output_fix.latitude: 599402240
07:34:10.144 > output_fix.lat_NS: N
07:34:10.144 > output_fix.longitude: 106774372
07:34:10.144 > output_fix.lon_EW: E
07:34:10.145 > --- gnss good average fix end
07:34:10.145 > gnss set RTC
07:34:10.145 > gnss turn off
07:34:10.145 > gnss enable low
07:34:10.247 > gnss end uart
07:34:10.346 > gnss done turn off
07:34:10.346 > gnss done average fix
07:34:10.346 > setup write boot message
07:34:11.292 > setup done
07:34:11.292 > loop start
07:34:11.292 > - TimeManager -
07:34:11.292 > posix_is_set: 1
07:34:11.292 > posix_timestamp: 1678343641
07:34:11.293 > gregorian: 2023-03-09T06:34:01
07:34:11.293 > ---------------
07:34:11.295 > sleep for (s): 359
07:34:11.395 > sleep for 359 seconds
07:40:11.815 > wakeupstart new measurement cycle
07:40:11.815 > get start fix
07:40:11.815 > gnss get good averaged fix
07:40:11.815 > gnss turn on
07:40:11.815 > gnss enable high
07:40:11.917 > gnss start serial
07:40:12.028 > gnss send commands
07:40:12.229 > gnss done turn on
07:40:12.327 > gnss get first fix
07:40:12.327 > gnss start grab uart output
07:40:12.328 > $PGACK,105*46
07:40:12.329 > gnss received NMEA end
[plenty of output while tries to get a GPS fix, then pushing the start fix; this scrolled out of my history before I could capture it]
07:42:16.895 > --- gnss good average fix end
07:42:16.896 > gnss set RTC
07:42:16.896 > gnss turn off
07:42:16.896 > gnss enable low
07:42:16.998 > gnss end uart
07:42:17.096 > gnss done turn off
07:42:17.097 > gnss done average fix
07:42:17.099 > enable burst mode
07:42:17.598 > log data
07:42:17.598 > clear data manager
07:42:17.797 > started ArtemisWire
07:42:17.797 > start the IMU
07:42:17.899 > Adafruit ISM330DHCX start!
07:42:17.907 > ISM330DHCX Found!
07:42:17.907 > start bmp390 1
07:42:17.927 > bmp390 1 started
07:42:19.026 > accel gyro info
07:42:19.026 > Accelerometer range set to: +-2G
07:42:19.026 > Gyro range set to: 125 degrees/s
07:42:19.026 > Accelerometer data rate set to: 833 Hz
07:42:19.027 > Gyro data rate set to: 833 Hz
07:50:23.505 > disable burst mode
07:50:24.002 > get end fix
07:50:24.002 > gnss get good averaged fix
07:50:24.002 > gnss turn on
07:50:24.002 > gnss enable high
07:50:24.104 > gnss start serial
07:50:24.214 > gnss send commands
07:50:24.416 > gnss done turn on
07:50:24.514 > gnss get first fix
07:50:24.514 > gnss start grab uart output
07:50:24.515 > $GPVTG�$PGACK,103*40
07:50:24.878 > gnss received NMEA end
07:50:24.880 > $PGACK,105*46
07:50:24.894 > gnss received NMEA end
07:50:24.895 > $PMTK011,MTKGPS*08
07:50:24.915 > gnss received NMEA end
07:50:24.916 > $PMTK010,001*2E
07:50:24.933 > gnss received NMEA end
07:50:24.933 > $PMTK010,002*2D
[plenty of output...]
07:51:22.890 > gnss received NMEA end
07:51:22.890 > $GPGSV,2,2,07,17,19,117,35,33,18,209,,10,14,334,28*49
07:51:22.947 > gnss received NMEA end
07:51:22.947 > $GPRMC,065122.000,A,5956.4113,N,01040.6512,E,0.01,42.27,090323,,,A*58
07:51:23.021 > gnss received NMEA end
07:51:23.021 > gnss NMEA parsed valid
07:51:23.021 > gnss NMEA is RMC
07:51:23.022 > gnss fill output fix
07:51:23.022 > gnss compute nsigma fix
07:51:23.024 > --- gnss good average fix start
07:51:23.024 > output_fix.posix_timestamp: 1678344660
07:51:23.024 > output_fix.year: 2023
07:51:23.025 > output_fix.month: 3
07:51:23.025 > output_fix.day: 9
07:51:23.025 > output_fix.hour: 6
07:51:23.025 > output_fix.minute: 51
07:51:23.025 > output_fix.latitude: 599401875
07:51:23.026 > output_fix.lat_NS: N
07:51:23.026 > output_fix.longitude: 106775228
07:51:23.027 > output_fix.lon_EW: E
07:51:23.027 > --- gnss good average fix end
07:51:23.027 > gnss set RTC
07:51:23.027 > gnss turn off
07:51:23.027 > gnss enable low
07:51:23.129 > gnss end uart
07:51:23.228 > gnss done turn off
07:51:23.229 > gnss done average fix
07:51:23.230 > dump data
07:51:27.007 > done with logging cycle
07:51:27.105 > loop start
07:51:27.105 > - TimeManager -
07:51:27.105 > posix_is_set: 1
07:51:27.106 > posix_timestamp: 1678344664
07:51:27.106 > gregorian: 2023-03-09T06:51:04
07:51:27.106 > ---------------
07:51:27.106 > sleep for (s): 536
07:51:27.209 > sleep for 536 seconds
```

**Comment by jerabaul29** [comment]
Meanwhile on the SD card:

```
/media/jrmet/data> ls -lrth
total 736K
-rw-r--r-- 1 jrmet jrmet 170K jan.   1 01:00 2023-03-09-06-42.dat
-rw-r--r-- 1 jrmet jrmet  160 jan.   1 01:00 2023-03-09-06-34.dat
```

The one from 06-34 is a "boot" file, the one from 06-42 is a "data" file.

**Comment by jerabaul29** [comment]
Also, can it be:

"NOTE: for some reason I ignore, sometimes the files are not visible to my default file explorer GUI, but they are well visible to the ls command."

from: https://github.com/jvoermans/Wind_Input_V1/blob/logger_version_jr/README.md

**Comment by jerabaul29** [comment]
also note for now I only use 1 pressure sensor, with the default address.

**Comment by jvoermans** [comment]
I think all the wiring was correct. Also I pulled the latest version, and updated all the libraries, but I'll also check that again.

I did get a GPS fix, the coordinates are correct that I received. I used external antenna. Difference with your output is that after the fix you get:
`gnss compute nsigma fix
`
and a lot of other stuff. In my case, it just repeats the GPRMC message.

I have two BMP390's attached, one with the default 0x77 and the other with the second address, so in principle that shouldn't matter...

**Comment by jerabaul29** [comment]
That is weird. Are you really sure it is not just working as it should? How do your full log look like?

**Comment by jerabaul29** [comment]
It is normal that the GPS sends many many lines.

**Comment by jerabaul29** [comment]
And the actual high frequency logging is just one line

**Comment by jerabaul29** [comment]
Also you may need to let it run for 30 minutes or so, in case you are unlucky with the syncing, to be sure you get something on the SD card.

**Comment by jerabaul29** [comment]
(you can have a look at main.cpp to see the main flow structure of the program)

**Comment by jvoermans** [comment]
I've let it run for 5-10 minutes outdoors with GPS connection and no blue light blinking which was unexpected, it just kept on throwing the GPS messages. But I'll double check tmrw the wiring and sketch again, maybe I made a mistake...

**Comment by jerabaul29** [comment]
Can you let if for longer - at least 20-30 mins :) . If you are unlucky, otherwise, you can be:

- using 5 minutes to get the first fix (as "cold GPS fix" can take quite a while)
- sleep a bit which cuts down power to everything including the GPS if it has no additional battery
- using 5 minutes to get the "cold again GPS fix" second fix (and you may be stopping there if only being 5-10 mins outside)
- waiting up to 9 minutes until you get "in synch" with minutesUTC % 10 == 0
- using 5 more minutes to take one more "cold again GPS fix"
- finally taking 8 minutes of data and dumping them

Also note that the instrument always needs GPS fix to be able to work properly, ie it is not enough to be outside for 5-10 mins then go inside, you should run with full GPS access for the whole duration.

This may explain your issues, let me know how this goes :) .

**Comment by jvoermans** [comment]
Ok perhaps that's the reason then :)

In that case I'll bring it home and test on Saturday as I can't leave my laptop unattended for that long. I'll buy a few of those battery coins to put in GPS, which should make that easier :)

**Comment by jerabaul29** [comment]
:)

I did a few improvements and fixes, and one more test home, and all looks good on my end. I also have reduced the verbosity of the GPS stuff, so that there will not be all these GPS message stuffs that hide other more important information :) .

The parser is also in good shape now, see: https://github.com/jvoermans/Wind_Input_V1/tree/logger_version_jr/decoder .

**Comment by jvoermans** [comment]
Many thanks!

I also found this GPS shield, which at first I though would make the wiring
less messy:
https://www.sparkfun.com/products/13750
unfortunately it doesn't have an external antenna socket like the GPS
breakout. Adafruit has a shield including antenna socket (
https://www.adafruit.com/product/1272)  but they haven't connected the
enable pin. They say you can only save power by removing the power to the
shield all together...
I'll just stick with a bare shield and fix them on that :)

**Comment by jerabaul29** [comment]
ok.

Small updates to the parser, looks quite ok, see https://github.com/jvoermans/Wind_Input_V1/blob/logger_version_jr/decoder/script_decode.py ; in case of questions, just let me know :) .

![accD](https://user-images.githubusercontent.com/8382834/224153581-85717064-14dc-4294-8dad-bbc3374e0eba.png)
![press1](https://user-images.githubusercontent.com/8382834/224153588-85a4d5e1-71b7-4333-815b-4d544e46ed4f.png)

**Comment by jvoermans** [comment]
Perfect!
If it is working for me too this weekend, I'll take it for a walk on
stairs, that should give a very clear increase in the pressure :)

**Comment by jerabaul29** [comment]
(in theory the only thing now is that the press2 needs to be added, will do it tomorrow :) ).

**Comment by jerabaul29** [comment]
(and I will add yaw pitch roll too :) )

**Comment by jerabaul29** [comment]
(note that as we discussed, the timing accuracy is typically "minute accurate", but not much - no PPS now, though it could be added in theory with more work)

**Comment by jvoermans** [comment]
Problem was that I used the 3.3V pin instead of the Vin pin. Not sure why that's a problem though? Based on blinking of GPS it finds a fix in both cases.

Anyway, still some GPS problems. Serial says no GPS, but my GPS unit is blinking every 10s, so should have a fix?
Only an initial GPS stamp is written to a file on SD-card, nothing else.

```
17:41:58.155 > WindInput logger | https://github.com/jvoermans/Wind_Input_V1
17:41:58.156 > Compiled: Mar 10 2023, 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
17:41:58.156 > git branch: DUMMY | commit ID: DUMMY
17:41:58.165 > compiling hostname: DUMMY | username: DUMMY
17:41:58.177 > Chip ID: 15245007187966232465     
17:41:58.187 > ***** all user configs start *****
17:41:58.187 > use_usb: 1
17:41:58.187 > file_start_modulo_seconds: 600    
17:41:58.188 > ***** all user configs end   *****
17:41:59.317 > sleep for 11 seconds
17:42:11.900 > wakeupsetup init GPS, get first fix, set RTC clock
17:46:20.239 > --- gnss good average fix start       
17:46:20.239 > output_fix.posix_timestamp: 1678430760
17:46:20.239 > output_fix.year: 2023
17:46:20.240 > output_fix.month: 3
17:46:20.240 > output_fix.day: 10
17:46:20.240 > output_fix.hour: 6
17:46:20.240 > output_fix.minute: 46
17:46:20.241 > output_fix.latitude: -378150236       
17:46:20.241 > output_fix.lat_NS: S
17:46:20.241 > output_fix.longitude: 1449548057      
17:46:20.242 > output_fix.lon_EW: E
17:46:20.242 > --- gnss good average fix end
17:46:20.444 > setup write boot message
17:46:21.550 > setup done
17:46:21.550 > loop start
17:46:21.550 > - TimeManager -
17:46:21.550 > posix_is_set: 1
17:46:21.550 > posix_timestamp: 1678430761   
17:46:21.550 > gregorian: 2023-03-10T06:46:01
17:46:21.551 > ---------------
17:46:21.552 > sleep for (s): 239
17:46:21.652 > sleep for 239 seconds
17:50:21.787 > wakeupstart new measurement cycle
17:50:21.788 > get start fix
17:55:23.303 > ERR: timeout GNSS acquisition
18:00:25.843 > ERR: timeout GNSS acquisition
18:05:28.389 > ERR: timeout GNSS acquisition
18:10:30.935 > ERR: timeout GNSS acquisition
18:15:33.493 > ERR: timeout GNSS acquisition
18:20:36.034 > ERR: timeout GNSS acquisition
18:25:38.563 > ERR: timeout GNSS acquisition
18:30:41.067 > ERR: timeout GNSS acquisition
18:35:43.558 > ERR: timeout GNSS acquisition
18:40:46.042 > ERR: timeout GNSS acquisition
```

I'll solder a battery coin holder to the unit Monday, then I can try without interference from buildings in the city...

**Comment by jerabaul29** [comment]
Mmmh, this is really strange, I have not met this before, and I do not see how this can happen. Are you sure there is no bad contact or similar? Are you sure there does is a GPS fix, ie the red GPS light is blinking slowly?

But I can at least handle this by  recording even if no GPS fix after the initial fix has been taken.

**Comment by jerabaul29** [comment]
I can turn on again a bit more log on the GPS to try to get more information about what happens :)

**Comment by jerabaul29** [comment]
Tested overnight, with a fix that allows it to work even if no GPS, as long as the first GPS fix is ok, and it worked fine. Adding a few more features today, but I think the present state should already be a minimum viable product :)

**Comment by jerabaul29** [comment]
Pushed a few more tests and improvements, seems to work correctly on my end. Doing more tests today and tonight :) .

**Comment by jerabaul29** [comment]
Tests today look good. If GPS is lost, there is a "clock drift" for some reason (not sure why, probably related to the burst mode), but apart from this, looks quite good.
