### ISSUE TITLE
having a chat

### ISSUE THREAD

**Issue by jerabaul29** [jvoermans/Wind_Input_V1#24]
@jvoermans should we have a chat next week to discuss this + deployment brainstorming etc? What about Wednesday at 08 Oslo time (the other days in the morning I am actually taken), otherwise the week after Wednesday or Friday should work at 08 :) . Or in the evening Oslo time / morning Melbourne time next week :) .

**Comment by jvoermans** [comment]
Wednesday at 08 Oslo works for me, can you send an invite?

**Comment by jerabaul29** [comment]
Perfect :) I send it tomorrow :) .

**Comment by jerabaul29** [comment]
sent.
