### ISSUE TITLE
testing continued

### ISSUE THREAD

**Issue by jerabaul29** [jvoermans/Wind_Input_V1#35]
I did a few updates to the firmware and parser, tested over the weekend, and I think things look good on my end @jvoermans .

- see the SD files parser and an example at: https://github.com/jvoermans/Wind_Input_V1/tree/logger_version_jr/decoder
- see the firmware dump (so if you want you can re-use the exact same firmware I am using) at: https://github.com/jvoermans/Wind_Input_V1/tree/logger_version_jr/firmware_bins
- wiring: see readme at https://github.com/jvoermans/Wind_Input_V1/tree/logger_version_jr

Let me know if you have any questions / issues :) .

**Comment by jvoermans** [comment]
Thanks, saw all the work this morning. It is running here right now. Seems all is going well from the Serial. I'll update you on it after a few cycles...

**Comment by jerabaul29** [comment]
Amazing :) . I had it running here for the whole day doing just small minor changes, and things seemed fine, so I think it should be fine, but waiting for your confirmation :) .

Btw, the pressure sensor is really amazing - I just moved around the senso by a few cms, and the signal in the pressure is really clear :) .

**Comment by jerabaul29** [comment]
Wonder if this could be really interesting for doing in situ measurements not just on the sea ice but on open ocean conditions too. I think the OMB is much smaller (so much less flow disturbance etc) compared with anything that has existed before, so that could be interesting.

**Comment by jvoermans** [comment]
I've got 2 files of 156kB now, so there is definetely data in there. I haven't been able to decode them yet, as I'm running in python/windows problems with the scripts. I have to get back to you on that later as I have meeting soon!
[2023_03_13.zip](https://github.com/jvoermans/Wind_Input_V1/files/10952125/2023_03_13.zip)

**Comment by jerabaul29** [comment]
Yes, the files look very good :) Decoding them: (```fix_start``` is deactivated to "save time" during the cycle running, so it is expected that the ```fix_start``` has default value, but ```fix_end``` contains good fix data :) )

```***** Put the interpreter in UTC, to make sure no TZ issues
***** Put the interpreter in UTC, to make sure no TZ issues
crrt_file: PosixPath('/home/jrmet/Downloads/2023_03_13/2023-03-12T21-08-16.dat')
kind: 'data_file'
data: Data_Message(fix_start=GNSS_Packet(datetime_fix=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), latitude=0.0, longitude=0.0, valid=False), fix_end=GNSS_Packet(datetime_fix=datetime.datetime(2023, 3, 12, 21, 8, 16, tzinfo=datetime.timezone.utc), latitude=37.8154371, longitude=144.9541542, valid=True), accX=array([-0.02173233, -0.02716637, -0.00663948, ..., -0.03199577,
              0.04829597, -0.01509285], dtype=float32), accY=array([-1.7688198, -1.777874 , -1.7712326, ..., -1.7591591, -1.7482929,
             -1.7374268], dtype=float32), accZ=array([-9.541961, -9.546186, -9.548602, ..., -9.528681, -9.555242,
             -9.552223], dtype=float32), accD=array([9.7042465, 9.709967 , 9.711103 , ..., 9.68906  , 9.713635 ,
             9.708331 ], dtype=float32), pitch=array([ 0.11077881,  0.12182617,  0.11077881, ...,  0.0553894 ,
              0.01107788, -0.01107788], dtype=float32), roll=array([-169.49908, -169.48799, -169.49908, ..., -169.6763 , -169.66524,
             -169.66524], dtype=float32), press1=array([1012.36774, 1012.36865, 1012.3772 , ..., 1012.3348 , 1012.33905,
             1012.3248 ], dtype=float32), press2=array([850., 850., 850., ..., 850., 850., 850.], dtype=float32), loopidx=1)

crrt_file: PosixPath('/home/jrmet/Downloads/2023_03_13/2023-03-12T20-57-35.dat')
kind: 'data_file'
data: Data_Message(fix_start=GNSS_Packet(datetime_fix=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), latitude=0.0, longitude=0.0, valid=False), fix_end=GNSS_Packet(datetime_fix=datetime.datetime(2023, 3, 12, 20, 57, 35, tzinfo=datetime.timezone.utc), latitude=37.8154051, longitude=144.9541849, valid=True), accX=array([-0.04165459, -0.0325985 , -0.04105186, ..., -0.00543404,
              0.00724411, -0.02293968], dtype=float32), accY=array([-1.9161205, -1.9306087, -1.9112892, ..., -1.6951675, -1.777874 ,
             -1.7253532], dtype=float32), accZ=array([-9.52385  , -9.511776 , -9.526265 , ..., -9.5739565, -9.532906 ,
             -9.552223 ], dtype=float32), accD=array([9.714212, 9.70536 , 9.715998, ..., 9.722327, 9.69686 , 9.706561],
            dtype=float32), pitch=array([ 0.21044922,  0.21044922,  0.2215271 , ..., -0.01107788,
             -0.01107788,  0.        ], dtype=float32), roll=array([-168.61293, -168.60185, -168.60185, ..., -169.76492, -169.70955,
             -169.70955], dtype=float32), press1=array([1012.29016, 1012.27856, 1012.27856, ..., 1012.335  , 1012.3423 ,
             1012.33624], dtype=float32), press2=array([850., 850., 850., ..., 850., 850., 850.], dtype=float32), loopidx=0)

```

**Comment by jvoermans** [comment]
Thanks for checking. I see the second BMP390 didn't work though. I have that one at the second address 0x76. Is that in the script as well?

**Comment by jerabaul29** [comment]
I only have 1 BMP390 myself, so for now, only 1 of them is in use in the code. I can add the second one now, I let you know for testing. (note that I have no way to test it myself, so there may be issues at first, but let us iterate :) ).

**Comment by jvoermans** [comment]
Yes sorry, I just see the BMP nr2 are commented out in the sensor_manager :)

**Comment by jerabaul29** [comment]
Just pushed one with 2 BMPs. There were a few more places to modify / uncomment, so use the pushed version :) . I also pushed the pre compiled firmware. Let me know if there are any issues!

**Comment by jvoermans** [comment]
Cool. I finally managed to get one with GPS reception. It is difficult between the high-rise buildings here :)
[2023-03-12T22-48-38.zip](https://github.com/jvoermans/Wind_Input_V1/files/10952308/2023-03-12T22-48-38.zip)

**Comment by jerabaul29** [comment]
Worked perfectly fine, both acceleration, both pressure sensors, and GPS data look good :) .

Then if you can do "as much extra testing as possible" that is great (in case we can find some bugs to be fixed :) ), but I think this is mostly ready :) .

![press2](https://user-images.githubusercontent.com/8382834/224641756-9da6a205-b13f-4ed4-83e2-559eff30bf57.png)
![press1](https://user-images.githubusercontent.com/8382834/224641761-e0373f6b-ecdd-43ce-a3ce-95b16380308d.png)
![accD](https://user-images.githubusercontent.com/8382834/224641763-4806a9f5-9a52-4d75-92f7-e7f953dd80fa.png)
